### ISSUE TITLE
v1.18 failed with config file mounted

### ISSUE THREAD

**Issue by MyDigitalLife** [nginxinc/docker-nginx-unprivileged#37]
I have a project that has nginx in my docker-compose like this:
```
  nginx:
    image: nn-docker.artifactory.prd.ss.aws.insim.biz/nginxinc/nginx-unprivileged:1.18-alpine
    ports:
      - "8081:8081"
    volumes:
    - "./../etc/nginx.conf:/etc/nginx/nginx.conf"
```

But on v1.18 i am getting the following errors:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-configure-nginx-unprivileged.sh
sed: can't move '/etc/nginx/nginx.confMDbjOE' to '/etc/nginx/nginx.conf': Resource busy
```

Going back to version 1.17.x works fine. What is the issue here? Am I configuring something incorrectly or is this a bug?
