### ISSUE TITLE
1.19.2-alpine fails to run "/var/cache/nginx/client_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by tvvignesh** [nginxinc/docker-nginx-unprivileged#50]
Hi. I tried to run 1.19.2-alpine and I get a lot of permission errors.

Screenshot:

<img width="353" alt="Capture" src="https://user-images.githubusercontent.com/1165845/95274534-b6683800-0863-11eb-95fd-3fc771ffb04b.png">

**Comment by alessfg** [comment]
Are you sure you are using this image and not the normal one?

**Comment by tvvignesh** [comment]
@alessfg Yup. I am using this image. Not the normal nginx. Tried running with privileged PSP in the cluster and it fails to run. Tried 1.18-alpine, 1.19-alpine, 1.19-alpine-amd64 and all of them don't run. Not sure if I am making any mistake but rebuilt it many times and it does not work.

**Comment by alessfg** [comment]
It must be your NGINX config then. Somewhere somehow NGINX is trying to create the `/var/cache/nginx/client_temp` directory, and that will always fail in an unprivileged system.

**Comment by tvvignesh** [comment]
@alessfg Hmm.. Will test it again and reply back tomorrow.

**Comment by tvvignesh** [comment]
@alessfg Did some debugging and got it working.

I had the mount path set to `/etc/nginx/nginx.conf` - replacing that with `/etc/nginx/conf.d/default.conf` removed the client_temp error:

```yml
volumeMounts:
            - name: tc-svc-app-config
              # mountPath: /etc/nginx/nginx.conf
              mountPath: /etc/nginx/conf.d/default.conf
              # subPath: nginx.conf
              subPath: default.conf
```

and ofcourse I had to change the config a bit cause I am no longer editing nginx conf but rather default conf. So, removed worker_processes, pid, http block and so on.

Not sure why I am not able to mount `nginx.conf` though. Even though its removed from the image, isn't it still valid?
